# rename this file to config.yml
telegramToken: 'token-here'
channelId: -10012345 # https://gist.github.com/mraaroncruz/e76d19f7d61d59419002db54030ebe35
admins:
  - 67890  # put admins' IDs here
  - 12300
adminTimeoutMinutes: 15
