name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get update && sudo apt-get install -y tesseract-ocr
      - run: npm install
      - run: npx gts check
      - run: npm run compile
      - run: npm test
